spring:
  application:
    name: scc-client
  config:
    import: "configserver:"

management:
  endpoint:
    env:
      show-values: always
  endpoints:
    web:
      exposure:
        include: "env"